FROM node:alpine

MAINTAINER thisbounty.com

VOLUME /mnt

# Install Mean.JS packages
RUN npm install
# Update & upgrade software and repository lists
RUN apk update
RUN apk upgrade
# Install software needed by WebRTC-frontend
RUN apk add make
RUN apk add python
RUN apk add g++
RUN apk add git
RUN npm install -g gulp

# Port 8080 for frontend
# Port 35729 for livereload
EXPOSE 8080 35729
